version: "3"
services:
  db:
    image: postgres:15-alpine3.18
    container_name: pg
    ports:
      - 5431:5432
    volumes:
      - ./PG_DB_DATA:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: docker_test
      PG_DATA: /var/lib/postgresql/data
    restart: always
  backend:
    image: 76b424a5e044
    container_name: pubg_tournament_server
    volumes:
      - /opt/backend/
    ports:
      - 8080
    environment:
      POSTGRES_HOST: host.docker.internal
    restart: always
    depends_on:
      - db
  nginx:
    image: nginx:1.24.0-alpine
    container_name: nginx
    volumes:
      - ./nginx_conf/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8989:8989
    restart: always
    depends_on:
      - backend
  client:
    image: ce7c4e03a910
    container_name: react_client
    volumes:
      - /opt/client/
    ports:
      - 3000:3000
    environment:
      POSTGRES_HOST: host.docker.internal
    depends_on:
      - nginx
      - backend
    restart: always




    #volumes:
#  PG_DB_DATA: